name: status_page
description: Library to consume Atlassian's Status Page API from dart.
version: 0.1.3
homepage: https://github.com/Fondeadora/status_page_dart

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.4
  equatable: ^2.0.3
  retrofit: ^3.0.1
  json_annotation: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  retrofit_generator: ^4.0.0
  build_runner: any
  json_serializable: ^6.1.3
